### ISSUE TITLE
Why Aurelia?

### ISSUE THREAD

**Issue by neverfox** [Aesthetickz/aurelia-flux#1]
This is a great example, but I have to ask, after integrating all the Flux stuff, do you find that using Aurelia is worth it as a view layer and why? It almost seems like it would be better to make the leap all the way to a React view layer (and there's no shortage of React/Flux frameworks out there) and get the benefit of that huge community. I inquire sincerely because I'm spending time lately considering which direction I want to go in the framework universe. I come from a Durandal.js (which is why I had my eye on Aurelia in the first place) and Ember.js background, but I had an epiphany of sorts after spending some time with the ClojureScript frameworks Reagent and Om. I'm really sold on unidirectional, FRP, immutable approaches to state in UI. I'm not married to React as a view layer by any means, but the large number of off-the-shelf components is tempting.

**Comment by Aesthetickz** [comment]
I come from an AngularJS background. I do find Aurelia quite elegant and I agree with Rob's idea's but I like React better for the View layer. Especially when using Flux, they just play so nicely together with the unidirectional data flow.
